Implement input normalization algorithm.

In [1]:
import numpy as np

class Normalizer:
    def __init__(self):
        self.mean = None
        self.std = None

    def fit(self, X):
        """Compute mean and std for each feature."""
        self.mean = np.mean(X, axis=0)
        self.std = np.std(X, axis=0)
        # Avoid division by zero
        self.std[self.std == 0] = 1e-8

    def transform(self, X):
        """Apply normalization using previously computed mean/std."""
        return (X - self.mean) / self.std

    def fit_transform(self, X):
        """Fit to data, then transform."""
        self.fit(X)
        return self.transform(X)

    def inverse_transform(self, X_norm):
        """Revert normalized data back to original scale."""
        return X_norm * self.std + self.mean


# ---- Example usage ----
np.random.seed(0)
X = np.random.randint(0, 100, size=(5, 3)).astype(float)  # 5 samples, 3 features
print("Original data:\n", X)

scaler = Normalizer()
X_norm = scaler.fit_transform(X)

print("\nNormalized data:\n", X_norm)
print("\nMean:", scaler.mean)
print("Std:", scaler.std)

# Optional: recover original
X_original = scaler.inverse_transform(X_norm)
print("\nRecovered data:\n", X_original)


Original data:
 [[44. 47. 64.]
 [67. 67.  9.]
 [83. 21. 36.]
 [87. 70. 88.]
 [88. 12. 58.]]

Normalized data:
 [[-1.78420724  0.15308204  0.48610445]
 [-0.40713454  1.00353779 -1.57049131]
 [ 0.55082908 -0.95251044 -0.56088975]
 [ 0.79031998  1.13110615  1.38352806]
 [ 0.85019271 -1.33521553  0.26174855]]

Mean: [73.8 43.4 51. ]
Std: [16.70209568 23.5168025  26.74322344]

Recovered data:
 [[44. 47. 64.]
 [67. 67.  9.]
 [83. 21. 36.]
 [87. 70. 88.]
 [88. 12. 58.]]
