Implement a convolution algorithm without padding and without striding for original image 6 x 6 and filter 3 x 3.

In [1]:
import numpy as np

# 6x6 original image (example values)
image = np.array([
    [1, 2, 0, 3, 1, 2],
    [4, 1, 0, 1, 0, 1],
    [1, 3, 2, 2, 3, 0],
    [2, 1, 3, 1, 1, 2],
    [0, 1, 2, 4, 2, 1],
    [1, 0, 3, 2, 1, 0]
])

# 3x3 filter (kernel)
kernel = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1]
])

# Output dimensions
output_size = image.shape[0] - kernel.shape[0] + 1
output = np.zeros((output_size, output_size))

# Convolution operation
for i in range(output_size):
    for j in range(output_size):
        # Extract current region of the image
        region = image[i:i+kernel.shape[0], j:j+kernel.shape[1]]
        # Element-wise multiply and sum
        output[i, j] = np.sum(region * kernel)

print("Output feature map (4x4):")
print(output)


Output feature map (4x4):
[[ 5. 10.  7.  7.]
 [12.  6.  6.  8.]
 [ 6. 13. 10.  8.]
 [10.  6. 12.  7.]]
